// Package card provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package card

// Card defines model for Card.
type Card struct {
	CardNo string `json:"card_no"`
}
